### ISSUE TITLE
Unclear error message when svn status fails

### ISSUE THREAD

**Issue by billsacks** [ESMCI/manage_externals#100]
### Summary of Issue:

When an `svn status` command fails in the course of running `checkout_externals -S`, the error message is unclear.

### Expected behavior and actual behavior:

An example of the actual behavior is:

```
$ ./manage_externals/checkout_externals -S --no-logging
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CLM.cfg
Processing externals description file : Externals_POP.cfg
Processing externals description file : Externals_CISM.cfg
Checking status of externals: clm, fates, ptclm, mosart, ww3, cime, cice, pop, no element found: line 9, column 0
```

Running with backtrace gives:

```
$ ./manage_externals/checkout_externals -S --no-logging --backtrace
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CLM.cfg
Processing externals description file : Externals_POP.cfg
Processing externals description file : Externals_CISM.cfg
Checking status of externals: clm, fates, ptclm, mosart, ww3, cime, cice, pop, no element found: line 9, column 0
Traceback (most recent call last):
  File "./manage_externals/checkout_externals", line 30, in <module>
    RET_STATUS, _ = manic.checkout.main(ARGS)
  File "/glade2/scratch2/sacks/cesm_code/cesm_testPop/manage_externals/manic/checkout.py", line 332, in main
    tree_status = source_tree.status()
  File "/glade2/scratch2/sacks/cesm_code/cesm_testPop/manage_externals/manic/sourcetree.py", line 263, in status
    stat = self._all_components[comp].status()
  File "/glade2/scratch2/sacks/cesm_code/cesm_testPop/manage_externals/manic/sourcetree.py", line 120, in status
    self._repo.status(self._stat, self._repo_dir_path)
  File "/glade2/scratch2/sacks/cesm_code/cesm_testPop/manage_externals/manic/repository_svn.py", line 88, in status
    self._status_summary(stat, repo_dir_path)
  File "/glade2/scratch2/sacks/cesm_code/cesm_testPop/manage_externals/manic/repository_svn.py", line 177, in _status_summary
    is_dirty = self.xml_status_is_dirty(svn_output)
  File "/glade2/scratch2/sacks/cesm_code/cesm_testPop/manage_externals/manic/repository_svn.py", line 208, in xml_status_is_dirty
    xml_status = ET.fromstring(svn_output)
  File "/glade/u/apps/ch/opt/python/2.7.14/intel/17.0.1/lib/python2.7/xml/etree/ElementTree.py", line 1312, in XML
    return parser.close()
  File "/glade/u/apps/ch/opt/python/2.7.14/intel/17.0.1/lib/python2.7/xml/etree/ElementTree.py", line 1671, in close
    self._raiseerror(v)
  File "/glade/u/apps/ch/opt/python/2.7.14/intel/17.0.1/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: no element found: line 9, column 0
```

It would be nice if the svn error were caught by manage_externals and it gave you a nice error message like:

```
Error running svn status from path/to/component
```

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

From cesm2_0_alpha10e: Remove components/pop. Replace it with an svn checkout of pop done with an older version of svn. Issuing an `svn status` from components/pop should then give:

```
$ svn status
svn: E155036: Please see the 'svn upgrade' command
svn: E155036: The working copy at '/glade2/scratch2/sacks/cesm_code/cesm_testPop/components/pop'
is too old (format 10) to work with client version '1.8.10 (r1615264)' (expects format 31). You need to upgrade the working copy first.
```

This gives a non-zero return value, but apparently that isn't caught by manage_externals.

checkout_externals gives the above, cryptic error message

### What is the changeset ID of the code, and the machine you are using:

manic-v1.1.3. On cheyenne, with `svn, version 1.8.10 (r1615264)`, 

### have you modified the code? If so, it must be committed and available for testing:

No

### Screen output or log file showing the error message and context:

See above

**Comment by billsacks** [comment]
It looks like the svn commands in repository_svn generally don't check the return code. It seems like they should.
